name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my_chess_engine .

    - name: Run Container
      run: docker run --name chess_engine_instance -d my_chess_engine

    - name: Wait for Container to Start
      run: sleep 10

    - name: Execute Tests
      run: docker exec chess_engine_instance /usr/src/app/tests/EngineStarterTest/EngineStarterTest

    - name: Check if Container is Running
      run: docker ps | grep chess_engine_instance
