name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my_chess_engine .

    - name: Run Container
      run: docker run --name chess_engine_instance -d my_chess_engine

    - name: Execute Tests
      run: docker exec chess_engine_instance /usr/src/app/tests/EngineStarterTest/EngineStarterTest
    
    - name: Cleanup
      run: docker rm -f chess_engine_instance

